package(default_visibility = ["//visibility:public"])

cc_library(
    name = "image_process",
    hdrs = ["image_process.h"],
    deps = [
        "//envpool/core:array",
        "@opencv",
    ],
)

